export const host = process.env.NEXT_PUBLIC_HOST || "http://127.0.0.1:8000";
export const repoAnalysisRoute = `${host}/api/analyze`
export const fileAnalysisRoute = `${host}/api/file`
export const askAssistantRoute = `${host}/api/ask`
export const repoVerifyRoute = `${host}/api/verify`
export const progressRoute = `${host}/api/progress`
export const authSignupRoute = `${host}/api/auth/signup`
export const authLoginRoute = `${host}/api/auth/login`
export const authMeRoute = `${host}/api/auth/me`
export const userHistoryRoute = `${host}/api/user/history`
export const userHistoryNotesRoute = `${host}/api/user/history/notes`